config/routes.rb
Rails.application.routes.draw do
  # mount Ckeditor::Engine => '/ckeditor'
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  root "static_pages#home"

  resources :artists, except: [:new, :create, :edit, :update, :destroy]
  resources :collections, except: [:new, :create, :edit, :update, :destroy]
  resources :documents, except: [:new, :create, :edit, :update, :destroy]
  resources :finding_aids, except: [:new, :create, :edit, :update, :destroy]
  resources :gaelic_athletes, except: [:new, :create, :edit, :update, :destroy]
  resources :series, except: [:new, :create, :edit, :update, :destroy]
  resources :songs, except: [:new, :create, :edit, :update, :destroy]

  #Static pages
  # Currently undefined:
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "rights-statement" => "static_pages#rights_statement"
  get "song-rights" => "static_pages#song_rights"
  get "tamiment-library" => "static_pages#tamiment_library"
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :collection
  validates :aiamm, :refid, :artist_id, :presence => true
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

    def slug_candidates
    [
      :aiamm,
      [:aiamm, :refid],
      [:aiamm, :refid, :artist_id],
      [:aiamm, :refid, :artist_id, :id],
    ]
  end

  def should_generate_new_friendly_id?
    new_record? || slug.blank?
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  def index
    @songs = Song.all
  end

  # GET /songs/1
  def show
    @song = Song.friendly.find(params[:id])
    @related_song = Song.where(artist_id: @song.artist_id).where.not(id: @song.id).limit(6)
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to @song, notice: 'Song was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /songs/1
  def update
    if @song.update(song_params)
      redirect_to @song, notice: 'Song was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /songs/1
  def destroy
    @song.destroy
    redirect_to songs_url, notice: 'Song was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def song_params
      params.require(:song).permit(:name, :aiamm)
    end
end

app/views/songs/_song.html.erb
<tr>
  <td><%= song.description.html_safe  %></td>
  <td><%= song.duration %></td>
  <td><%= song.aiamm %></td>
</tr>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.description %></td>
        <td><%= song.duration %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/show.html.erb
<% provide(:title, @song.name + ": " + @song.title) %>
<div class='container'>
  <div class="bread">
    <span class='bread_first'><%= @song.name.upcase %>: </span><span class='bread_second'> <%= @song.title.upcase %></span>
  </div>
  <div class='page_intro'>
    <div class='song_player'>
      <div class="embed_wrapper">
        <%= image_tag(@song.thumbnail) %>
      </div>
      <div class="song_metadata">
        <div class="song_title"><%= @song.name.upcase %>: <%= @song.title.upcase %> &nbsp; &nbsp; (<%= @song.duration %>)</div>
        <div class="song_description"><%= @song.description.html_safe %></div>
        <% if @song.transcript? %>
          <p class="float-right"><strong><%= link_to "TRANSCRIPT", @song.transcript.url %></strong></p>
        <% end %>
        <ul class="song_social">
         <li><a onclick="window.open('http://twitter.com/share','C2G','menubar=no,width=550,height=250,toolbar=no'); return false;" href="#"><%= icon('twitter') %></i></a></li>
         <li><a href="#" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href), 'facebook-share-dialog', 'width=626,height=436'); return false;"><%= icon('facebook') %></i></a></li>
         <li><a href="mailto:?subject=Mick%20Moloney%20Collection&body=<%= @song.name+ ": " + @song.title + "%0A" + request.original_url %>"><%= icon('envelope') %></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class='song_grid'>
    <h4>RELATED SONGS</h4>
      <%= render @related_song  %>
    </div>
  </div>