config/routes.rb
Rails.application.routes.draw do
  # mount Ckeditor::Engine => '/ckeditor'
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  root "static_pages#home"

  resources :artists, except: [:new, :create, :edit, :update, :destroy]
  resources :collections, except: [:new, :create, :edit, :update, :destroy]
  resources :documents, except: [:new, :create, :edit, :update, :destroy]
  resources :finding_aids, except: [:new, :create, :edit, :update, :destroy]
  resources :gaelic_athletes, except: [:new, :create, :edit, :update, :destroy]
  resources :series, except: [:new, :create, :edit, :update, :destroy]
  resources :songs, except: [:new, :create, :edit, :update, :destroy]

  #Static pages
  # Currently undefined:
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "rights-statement" => "static_pages#rights_statement"
  get "song-rights" => "static_pages#song_rights"
  get "tamiment-library" => "static_pages#tamiment_library"
end

app/models/document.rb
class Document < ApplicationRecord
  validates :title, :document_file_file_name,  :presence => true
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  has_attached_file :document_file, :styles => { :small => "350x350#" }, :default_url => "/system/documents/default_doc.jpg"
  validates_attachment_content_type :document_file, :content_type => /\Aimage\/.*\Z/

  def slug_candidates
    [
      :title,
      [:title, :identifier],
      [:title, :identifier, :id]
    ]
  end

  def should_generate_new_friendly_id?
    new_record? || slug.blank?
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.all
    @other_docs = Document.order("RAND()").limit(12)
  end

  def show
    @document = Document.friendly.find(params[:id])
    @other_docs = Document.where.not(id: @document.id).order("RAND()").limit(12)
  end

  private

    def document_params
      params.require(:document).permit(:title)
    end
end

app/views/documents/_document.html.erb
  <div class="<% if document_counter == 0 %> col-xs-12 <% else %> col-xs-6 <% end %>doc_grid">
      <%= link_to image_tag(document.document_file(:small), class: "document_img"), document_path(document.slug) %>
      <% if document_counter == 0 %>
        <div class='col-xs-12'>
          <%= document.title.upcase %>
        </div>
      <% end %>
  </div>

app/views/documents/_random_docs.html.erb
<% @other_docs.each do |doc| %>
  <div class='col-xs-3 col-md-2 doc_grid_item'>
    <%= link_to image_tag(doc.document_file(:small), class: "document_img"), document_path(doc.slug) %>
  </div>
<% end %>

app/views/documents/index.html.erb
<% provide(:title, "Documents") %>
<div class='container-fluid'>
  <h4>DOCUMENTS</h4>
  <p>
    The Mick Moloney Irish Americana collection consists of printed ephemera and published music documenting not only the development of musical traditions, but also the Irish and Irish American image in popular culture, with particular emphasis on ethnic perceptions and representations. A selection of the sheet music in this collection has been digitized and can be found here, with a fuller range available through the collection’s finding aid. The sheet music in the collection was published between 1817 and 1995, with the majority dating from between 1860 and 1930. The collection includes sheet music in a variety of sizes and styles: simple sheet music published using black and white lithographs from the 1800s, Tin Pan Alley publications of dramatic ballads and novelty songs from the late 19th and early 20th centuries, sheet music with highly stylized and colorful illustrations, and sheet music featuring portraits of prominent singers or actors. A wide range of themes and subjects are present, including comedic, novelty, sentimental, nostalgic, and political. The seepage of entertainment from public venues such as vaudeville into the domestic sphere created demand for such sheet music, and is inextricably tied to the emergence of the American middle class and its culture of consumption.
  </p>
</div>
<div class='container-fluid grey_section'>
  <div class='row'>
    <h6>CURATED DOCS OR RANDOM LIST</h6>
    <div class='col-xs-12 doc_page_grid'>
      <%= render partial: "random_docs", action: @other_docs  %>
    </div>
  </div>
</div>

app/views/documents/show.html.erb
<% provide(:title, @document.title) %>
<h4>DOCUMENT: <%= @document.title.upcase %></h4>
<div class='container-fluid'>
  <div class='row grey_section'>
    <div class='col-xxs col-xs-6 col-md-6 pull-right doc_img'>
      <%= image_tag(@document.document_file.url) %>
    </div>
    <div class='col-xxs col-xs-6 col-md-4 pull-left doc_desc'>
      <p><%= @document.description.html_safe %></p>
      <p><%= @document.identifier %></p>
    </div>
  </div>
</div>
<div class='container-fluid'>
  <div class='row'>
    <h6>EXPLORE THE COLLECTION</h6>
    <div class='col-xs-12 doc_page_grid'>
        <%= render partial: "random_docs", action: @other_docs  %>
    </div>
  </div>
</div>