config/routes.rb
Rails.application.routes.draw do
  # mount Ckeditor::Engine => '/ckeditor'
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  root "static_pages#home"

  resources :artists, except: [:new, :create, :edit, :update, :destroy]
  resources :collections, except: [:new, :create, :edit, :update, :destroy]
  resources :documents, except: [:new, :create, :edit, :update, :destroy]
  resources :finding_aids, except: [:new, :create, :edit, :update, :destroy]
  resources :gaelic_athletes, except: [:new, :create, :edit, :update, :destroy]
  resources :series, except: [:new, :create, :edit, :update, :destroy]
  resources :songs, except: [:new, :create, :edit, :update, :destroy]

  #Static pages
  # Currently undefined:
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "rights-statement" => "static_pages#rights_statement"
  get "song-rights" => "static_pages#song_rights"
  get "tamiment-library" => "static_pages#tamiment_library"
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def show
    @series = Series.friendly.find(params[:id])
  end

  private

    def series_params
      params.require(:series).permit(:title, :description)
    end
end

app/views/series/_series.html.erb
<!-- START SERIES --> 
<div class='container-fluid grey_section' id="series_<%= series.id %>">
  <h6><%= series.title.upcase %></h6>
  <div class='row'>
    <div class='col-xs-12 finding_aid_table'>
        <%= series.table.html_safe %>
    </div>
  </div>
</div>

app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Series</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.title %></td>
        <td><%= series.description %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Edit', edit_series_path(series) %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/show.html.erb
<!-- START SERIES --> 
<div class='container-fluid'>
  <h6><%= @series.finding_aid.title.upcase %></h6>
  <div class='row'>
    <div class='col-xs-12 finding_aid_table'>
        <h5><%= @series.title %></h5>
        <%= @series.table.html_safe %>
    </div>
  </div>
</div>