config/routes.rb
Rails.application.routes.draw do
  # mount Ckeditor::Engine => '/ckeditor'
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)

  root "static_pages#home"

  resources :artists, except: [:new, :create, :edit, :update, :destroy]
  resources :collections, except: [:new, :create, :edit, :update, :destroy]
  resources :documents, except: [:new, :create, :edit, :update, :destroy]
  resources :finding_aids, except: [:new, :create, :edit, :update, :destroy]
  resources :gaelic_athletes, except: [:new, :create, :edit, :update, :destroy]
  resources :series, except: [:new, :create, :edit, :update, :destroy]
  resources :songs, except: [:new, :create, :edit, :update, :destroy]

  #Static pages
  # Currently undefined:
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "rights-statement" => "static_pages#rights_statement"
  get "song-rights" => "static_pages#song_rights"
  get "tamiment-library" => "static_pages#tamiment_library"
end

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li><%= link_to "RIGHTS STATEMENT", :controller => :static_pages, :action => :rights_statement %></li>
      <li><a href="#">Link 2</a></li>
      <li><a href="#">Link 3</a></li>
      <li>© 2015 TAMIMENT LIBRARY</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class='header'>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <%= link_to "MOLONEY COLLECTION", root_path, :class => "navbar-brand"  =%>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
        <%= nav_link "ABOUT", about_path %>
        <%= nav_link "ARTISTS", artists_path %>
        <%= nav_link "GAELIC ATHLETES", gaelic_athletes_path %>
        <%= nav_link "DOCUMENTS", documents_path %>
        <%= nav_link "FINDING AIDS", finding_aids_path %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <% if current_page?('/') %>
    <div>
      <%= image_tag "home_banner.png" =%>
    </div>
  <% end %>

</div><!-- header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />

  <title><%= full_title(yield(:title)).html_safe %></title>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato' %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Roboto' %>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-55461631-24"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-55461631-24');
  </script>
  <%= render 'layouts/header' %>
  <div class='page_content'>
    <div class='page_wrap'>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= render "javascript" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </div>
</body>
</html>